name: PartNerd
favicon: null
layout_spectrum: 0.6265130867250264
typography_spectrum: 0.06560967955738306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6990386806428432
  lightness: 0.4389776815660298
  saturation: 0.1495335060171783
  rhythmicContrast: 0.6203001684043556
purpose: []
